import { Component,OnDestroy,OnInit,inject,signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { Bridge } from './bridge';
interface Game {salvage:number;level:number;armor:number;power:number;engine:number;last:number;}
@Component({selector:'sp-game',standalone:true,imports:[CommonModule,MatButtonModule,MatProgressBarModule],template:`
  <div class="game" (keydown)="keyboard($event)" tabindex="0" aria-label="Scrapbots game. Use arrow keys to pilot and space to attack.">
    <div class="row spread"><div><span class="eyebrow">Scrapbots · Sector {{game().level}}</span><h2>Something good in the scrap.</h2></div><span class="pill">{{game().salvage}} salvage</span></div>
    <div class="tabs"><button mat-button (click)="view.set('pilot')">Pilot</button><button mat-button (click)="view.set('skills')">Skill tree</button></div>
    @if(view()==='pilot'){
    <div class="arena" role="img" aria-label="Scrapyard arena. Your bot is the circle, guardians are hexagons, and the exit is at bottom right.">
      <svg viewBox="0 0 600 340"><defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" opacity=".12"/></pattern></defs><rect width="600" height="340" fill="url(#grid)"/>
      @for(rock of rocks;track $index){<rect [attr.x]="rock.x" [attr.y]="rock.y" width="35" height="35" rx="8" fill="var(--mat-sys-surface-container-highest)"/>}
      <rect x="530" y="260" width="55" height="55" rx="12" fill="var(--mat-sys-tertiary-container)"/><text x="557" y="294" text-anchor="middle" fill="var(--mat-sys-on-tertiary-container)" font-size="24">↗</text>
      @for(enemy of enemies();track enemy.id){<g [attr.transform]="'translate('+enemy.x+','+enemy.y+')'"><path d="M0 -17 L15 -9 L15 9 L0 17 L-15 9 L-15 -9Z" fill="var(--mat-sys-error-container)" stroke="var(--mat-sys-error)" stroke-width="2"/><text text-anchor="middle" y="5" fill="var(--mat-sys-on-error-container)" font-size="12">{{enemy.hp}}</text></g>}
      <circle [attr.cx]="position().x" [attr.cy]="position().y" r="18" fill="var(--mat-sys-primary)"/><circle [attr.cx]="position().x+5" [attr.cy]="position().y-4" r="5" fill="var(--mat-sys-on-primary)"/>
      @for(piece of loot();track piece.id){<path [attr.transform]="'translate('+piece.x+','+piece.y+')'" d="M0 -7L7 0L0 7L-7 0Z" fill="var(--mat-sys-tertiary)"/>}
      </svg>
    </div><div class="row spread"><div class="health"><span>Hull {{health()}} / {{100+game().armor*20}}</span><mat-progress-bar [value]="health()/(100+game().armor*20)*100"></mat-progress-bar></div><span>{{cargo()}} salvage onboard</span></div>
    <p class="status" aria-live="polite">{{status()}}</p>
    <div class="row wrap"><button mat-stroked-button aria-label="Move left" (click)="move(-25,0)">←</button><button mat-stroked-button aria-label="Move up" (click)="move(0,-25)">↑</button><button mat-stroked-button aria-label="Move down" (click)="move(0,25)">↓</button><button mat-stroked-button aria-label="Move right" (click)="move(25,0)">→</button><button mat-flat-button (click)="attack()">Pulse cannon</button><button mat-stroked-button (click)="extract()">Extract</button><button mat-button (click)="newMission()">New mission</button></div>
    }@else{
      <p class="muted">Your workshop collects one salvage per minute while you are away, up to eight hours. Upgrade your bot for the next mission.</p>
      <div class="skills">@for(skill of skills;track skill.key){<section class="panel"><span class="skill-icon">{{skill.icon}}</span><h3>{{skill.name}}</h3><p>{{skill.description}}</p><p>Level {{level(skill.key)}} · Cost {{cost(skill.key)}} salvage</p><button mat-flat-button [disabled]="game().salvage<cost(skill.key)" (click)="upgrade(skill.key)">Upgrade</button></section>}</div>
    }
  </div>`,styles:[`.game{display:flex;flex-direction:column;gap: var(--space-16);outline:none}.tabs{display:flex;gap: var(--space-8)}.arena{background:var(--mat-sys-surface-container-lowest);border-radius: var(--shape-lg);overflow:hidden;color:var(--mat-sys-on-surface)}svg{display:block;width:100%;max-height:calc(400px * var(--ui-scale))}.health{width:45%;display:flex;flex-direction:column;gap: var(--space-8)}.status{min-height:var(--space-24);color:var(--mat-sys-on-surface-variant)}.skills{display:grid;grid-template-columns:repeat(3,1fr);gap: var(--space-16)}.skills section{display:flex;flex-direction:column;gap: var(--space-16)}.skill-icon{font-size: var(--text-40);color:var(--mat-sys-primary)}`]})
export class GameComponent implements OnInit,OnDestroy {
  bridge=inject(Bridge);game=signal<Game>({salvage:0,level:1,armor:0,power:0,engine:0,last:Date.now()});view=signal('pilot');position=signal({x:60,y:60});health=signal(100);cargo=signal(0);status=signal('Collect salvage, defeat guardians, and reach the exit to extract.');enemies=signal([{id:1,x:300,y:120,hp:50},{id:2,x:420,y:240,hp:70}]);loot=signal(Array.from({length:8},(_,i)=>({id:i,x:120+i*50,y:80+(i%3)*70})));rocks=[{x:190,y:180},{x:390,y:50},{x:90,y:240}];skills=[{key:'armor' as const,name:'Reinforced hull',description:'+20 hull integrity per level.',icon:'⬡'},{key:'power' as const,name:'Pulse amplifier',description:'+10 cannon damage per level.',icon:'ϟ'},{key:'engine' as const,name:'Salvage drive',description:'Move faster and collect from farther away.',icon:'↗'}];
  async ngOnInit(){if(new URLSearchParams(location.search).has('skills'))this.view.set('skills');try{const saved=await this.bridge.call('game-read');if(saved.last){const elapsed=Math.min(480,Math.max(0,Math.floor((Date.now()-saved.last)/60000)));this.game.set({...this.game(),...saved,salvage:Number(saved.salvage??0)+elapsed,last:Date.now()});this.health.set(100+this.game().armor*20);}}catch(e){this.status.set((e as Error).message);}}
  level(key:'armor'|'power'|'engine'){return this.game()[key];}cost(key:'armor'|'power'|'engine'){return (this.level(key)+1)*25;}
  upgrade(key:'armor'|'power'|'engine'){const cost=this.cost(key);if(this.game().salvage<cost)return;this.game.update(g=>({...g,[key]:g[key]+1,salvage:g.salvage-cost}));void this.save();}
  move(dx:number,dy:number){if(this.health()<=0)return;const speed=1+this.game().engine*.1;this.position.update(p=>({x:Math.min(575,Math.max(25,p.x+dx*speed)),y:Math.min(315,Math.max(25,p.y+dy*speed))}));const p=this.position();const collected=this.loot().filter(l=>Math.hypot(l.x-p.x,l.y-p.y)<30+this.game().engine*5);if(collected.length){this.cargo.update(n=>n+collected.length*5);this.loot.update(list=>list.filter(l=>!collected.includes(l)));this.status.set('Salvage secured. Bring it to the exit.');}this.enemyTurn();}
  attack(){if(this.health()<=0)return;const p=this.position();const target=this.enemies().filter(e=>Math.hypot(e.x-p.x,e.y-p.y)<180).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(!target){this.status.set('No guardian in range. Move closer.');return;}this.enemies.update(list=>list.map(e=>e.id===target.id?{...e,hp:e.hp-25-this.game().power*10}:e).filter(e=>e.hp>0));if(!this.enemies().some(e=>e.id===target.id)){this.cargo.update(n=>n+15);this.status.set('Guardian dismantled. +15 salvage.');}else this.status.set('Pulse hit. Keep moving.');this.enemyTurn();}
  enemyTurn(){const p=this.position();let damage=0;this.enemies.update(list=>list.map(e=>{const distance=Math.hypot(e.x-p.x,e.y-p.y);if(distance<45){damage+=8;return e;}if(distance<230)return {...e,x:e.x+(p.x-e.x)/distance*14,y:e.y+(p.y-e.y)/distance*14};return e;}));this.health.update(h=>Math.max(0,h-damage));if(this.health()===0){this.cargo.set(0);this.status.set('Hull lost. Your workshop salvage is safe. Start a new mission.');}}
  extract(){if(this.health()<=0){this.status.set('Start a new mission to return to the scrapyard.');return;}if(Math.hypot(this.position().x-557,this.position().y-285)>70){this.status.set('Reach the exit at the bottom right to extract.');return;}this.game.update(g=>({...g,salvage:g.salvage+this.cargo(),level:g.level+1}));this.cargo.set(0);this.newMission();this.status.set('Extraction complete. Salvage delivered; your next sector is ready.');void this.save();}
  newMission(){this.position.set({x:60,y:60});this.health.set(100+this.game().armor*20);this.cargo.set(0);this.enemies.set([{id:1,x:300,y:120,hp:40+this.game().level*10},{id:2,x:420,y:240,hp:60+this.game().level*10}]);this.loot.set(Array.from({length:8},(_,i)=>({id:i,x:120+i*50,y:80+(i%3)*70})));this.status.set('A new sector awaits. Bring your bot home.');}
  keyboard(e:KeyboardEvent){if(e.key==='ArrowLeft')this.move(-25,0);else if(e.key==='ArrowRight')this.move(25,0);else if(e.key==='ArrowUp')this.move(0,-25);else if(e.key==='ArrowDown')this.move(0,25);else if(e.key===' ')this.attack();else return;e.preventDefault();}
  async save(){this.game.update(g=>({...g,last:Date.now()}));try{await this.bridge.call('game-save',this.game());}catch(e){this.status.set('Could not save: '+(e as Error).message);}}
  ngOnDestroy(){void this.save();}
}
